/* patisserie - A CLI for pastery.net
 * Copyright (C) 2025  Beth Rennie
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

use anyhow::anyhow;
use camino::Utf8Path;
use phf::phf_set;

pub fn parse_language(s: &str) -> Result<&'static str, anyhow::Error> {
    LANGUAGES
        .get_key(s)
        .copied()
        .ok_or_else(|| anyhow!("Unknown language `{}'", s))
}

pub fn guess_language(path: &Utf8Path) -> Option<&'static str> {
    path.file_name()
        .and_then(guess_language_by_filename)
        .or_else(|| path.extension().and_then(guess_language_by_ext))
}

fn guess_language_by_filename(filename: &str) -> Option<&'static str> {
    Some(match &*filename.to_ascii_lowercase() {
        "makefile" => "make",
        "cmakelists.txt" => "cmake",
        _ => return None,
    })
}

fn guess_language_by_ext(ext: &str) -> Option<&'static str> {
    Some(match &*ext.to_ascii_lowercase() {
        "sh" => "bash",
        "c" | "h" => "c",
        "cbl" | "cob" | "cpy" => "cobol",
        "cc" | "cpp" | "cxx" | "hh" | "hpp" | "hxx" => "cpp",
        "cs" => "csharp",
        "css" | "pcss" => "css",
        "d" => "d",
        "pas" => "delphi",
        "diff" => "diff",
        "ex" | "exs" => "elixir",
        "erl" | "hrl" => "erlang",
        "f" | "for" | "f90" | "f95" | "f03" => "fortran",
        "fs" => "fsharp",
        "go" => "go",
        "glsl" => "glsl",
        "htm" | "html" => "html",
        "ini" => "ini",
        "java" => "java",
        "json" => "json",
        "kt" | "kts" => "kotlin",
        "lua" => "lua",
        "mat" => "matlab",
        "m" => "objective-c",
        "mm" => "objective-c++",
        "nix" => "nixos",
        "php" => "php",
        "pl" | "pm" => "perl",
        "p" | "pro" => "prolog",
        "py" => "python3",
        "bas" => "qbasic",
        "r" => "r",
        "rs" => "rust",
        "rb" => "ruby",
        "sass" => "sass",
        "sc" | "scala" => "scala",
        "scm" => "scheme",
        "scss" => "scss",
        "sql" => "sql",
        "siwft" => "swift",
        "js" => "js",
        "tex" | "latex" => "tex",
        "txt" => "text",
        "ts" => "ts",
        "vb" => "vb.net",
        "vim" => "vim",
        "xml" => "xml",

        _ => return None,
    })
}

static LANGUAGES: phf::Set<&'static str> = phf_set! {
    "abap",
    "ada",
    "agda",
    "ahk",
    "alloy",
    "antlr",
    "antlr-as",
    "antlr-cpp",
    "antlr-csharp",
    "antlr-java",
    "antlr-objc",
    "antlr-perl",
    "antlr-python",
    "antlr-ruby",
    "apacheconf",
    "apl",
    "applescript",
    "as",
    "as3",
    "aspectj",
    "aspx-cs",
    "aspx-vb",
    "asy",
    "at",
    "autodetect",
    "autoit",
    "awk",
    "basemake",
    "bash",
    "bat",
    "bbcode",
    "befunge",
    "blitzbasic",
    "blitzmax",
    "boo",
    "brainfuck",
    "bro",
    "bugs",
    "c",
    "c-objdump",
    "ca65",
    "cbmbas",
    "ceylon",
    "cfc",
    "cfengine3",
    "cfm",
    "cfs",
    "chai",
    "chapel",
    "cheetah",
    "cirru",
    "clay",
    "clojure",
    "clojurescript",
    "cmake",
    "cobol",
    "cobolfree",
    "coffee-script",
    "common-lisp",
    "console",
    "control",
    "coq",
    "cpp",
    "cpp-objdump",
    "croc",
    "cryptol",
    "csharp",
    "css",
    "css+django",
    "css+erb",
    "css+genshitext",
    "css+lasso",
    "css+mako",
    "css+mozpreproc",
    "css+myghty",
    "css+php",
    "css+smarty",
    "cucumber",
    "cuda",
    "cypher",
    "cython",
    "d",
    "d-objdump",
    "dart",
    "delphi",
    "dg",
    "diff",
    "django",
    "docker",
    "dpatch",
    "dtd",
    "duel",
    "dylan",
    "dylan-console",
    "dylan-lid",
    "ebnf",
    "ec",
    "ecl",
    "eiffel",
    "elixir",
    "erb",
    "erl",
    "erlang",
    "evoque",
    "factor",
    "fan",
    "fancy",
    "felix",
    "fortran",
    "foxpro",
    "fsharp",
    "gap",
    "gas",
    "genshi",
    "genshitext",
    "glsl",
    "gnuplot",
    "go",
    "golo",
    "gooddata-cl",
    "gosu",
    "groff",
    "groovy",
    "gst",
    "haml",
    "handlebars",
    "haskell",
    "haxeml",
    "html",
    "html+cheetah",
    "html+django",
    "html+evoque",
    "html+genshi",
    "html+handlebars",
    "html+lasso",
    "html+mako",
    "html+myghty",
    "html+php",
    "html+smarty",
    "html+twig",
    "html+velocity",
    "http",
    "hx",
    "hybris",
    "hylang",
    "i6t",
    "idl",
    "idris",
    "iex",
    "igor",
    "inform6",
    "inform7",
    "ini",
    "io",
    "ioke",
    "ipython2",
    "ipython3",
    "ipythonconsole",
    "irc",
    "isabelle",
    "jade",
    "jags",
    "jasmin",
    "java",
    "javascript+mozpreproc",
    "jlcon",
    "js",
    "js+cheetah",
    "js+django",
    "js+erb",
    "js+genshitext",
    "js+lasso",
    "js+mako",
    "js+myghty",
    "js+php",
    "js+smarty",
    "json",
    "jsonld",
    "jsp",
    "julia",
    "kal",
    "kconfig",
    "koka",
    "kotlin",
    "lagda",
    "lasso",
    "lcry",
    "lean",
    "lhs",
    "lidr",
    "lighty",
    "limbo",
    "liquid",
    "live-script",
    "llvm",
    "logos",
    "logtalk",
    "lsl",
    "lua",
    "make",
    "mako",
    "maql",
    "markdown",
    "mask",
    "mason",
    "mathematica",
    "matlab",
    "matlabsession",
    "minid",
    "modelica",
    "modula2",
    "monkey",
    "moocode",
    "moon",
    "mozhashpreproc",
    "mozpercentpreproc",
    "mql",
    "mscgen",
    "mupad",
    "mxml",
    "myghty",
    "mysql",
    "nasm",
    "nemerle",
    "nesc",
    "newlisp",
    "newspeak",
    "nginx",
    "nimrod",
    "nit",
    "nixos",
    "nsis",
    "numpy",
    "objdump",
    "objdump-nasm",
    "objective-c",
    "objective-c++",
    "objective-j",
    "ocaml",
    "octave",
    "ooc",
    "opa",
    "openedge",
    "pan",
    "pawn",
    "perl",
    "perl6",
    "php",
    "pig",
    "pike",
    "plpgsql",
    "postgresql",
    "postscript",
    "pot",
    "pov",
    "powershell",
    "prolog",
    "properties",
    "protobuf",
    "psql",
    "puppet",
    "py3tb",
    "pycon",
    "pypylog",
    "pytb",
    "python",
    "python3",
    "qbasic",
    "qml",
    "racket",
    "ragel",
    "ragel-c",
    "ragel-cpp",
    "ragel-d",
    "ragel-em",
    "ragel-java",
    "ragel-objc",
    "ragel-ruby",
    "raw",
    "rb",
    "rbcon",
    "rconsole",
    "rd",
    "rebol",
    "red",
    "redcode",
    "registry",
    "resource",
    "rexx",
    "rhtml",
    "robotframework",
    "rql",
    "rsl",
    "rst",
    "rust",
    "sass",
    "scala",
    "scaml",
    "scheme",
    "scilab",
    "scss",
    "shell-session",
    "slim",
    "smali",
    "smalltalk",
    "smarty",
    "sml",
    "snobol",
    "sourceslist",
    "sp",
    "sparql",
    "spec",
    "splus",
    "sql",
    "sqlite3",
    "squidconf",
    "ssp",
    "stan",
    "swift",
    "swig",
    "systemverilog",
    "tads3",
    "tcl",
    "tcsh",
    "tea",
    "tex",
    "text",
    "textile",
    "todotxt",
    "trac-wiki",
    "treetop",
    "ts",
    "twig",
    "urbiscript",
    "vala",
    "vb.net",
    "vctreestatus",
    "velocity",
    "verilog",
    "vgl",
    "vhdl",
    "vim",
    "xml",
    "xml+cheetah",
    "xml+django",
    "xml+erb",
    "xml+evoque",
    "xml+lasso",
    "xml+mako",
    "xml+myghty",
    "xml+php",
    "xml+smarty",
    "xml+velocity",
    "xquery",
    "xslt",
    "xtend",
    "xul+mozpreproc",
    "yaml",
    "yaml+jinja",
    "zephir",
};
